config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from movies import views

urlpatterns = [
    path('', views.main, name="main"),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('community/', include('community.urls')),
    path('movies/', include('movies.urls'))
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

movies/urls.py
from django.urls import path
from . import views

app_name="movies"
urlpatterns = [
    path('', views.movie_index, name='movie_index'),
    path('<int:movie_pk>/', views.movie_detail, name='movie_detail'),
    path('<int:movie_pk>/reviews/<int:review_pk>/update/', views.movie_review_update, name='movie_review_update'),
    path('<int:movie_pk>/reviews/<int:review_pk>/delete/', views.movie_review_delete, name='movie_review_delete'),
    path('<int:movie_pk>/reviews/create/', views.movie_review_create, name='movie_review_create'),
    path('list/', views.movie_list, name='movie_list'),
    # tmdb
    path('tmdb_upcoming/', views.tmdb_upcoming, name="tmdb_upcoming"),
    path('tmdb_popular/', views.tmdb_popular, name="tmdb_popular"),
    path('tmdb_now_playing/', views.tmdb_now_playing, name="tmdb_now_playing"),
    path('face_recommends/', views.face_recommends, name="face_recommends"),
    path('tmdb_search/', views.tmdb_search, name="tmdb_search"),
    path('tmdb_detail/<int:movie_id>/', views.tmdb_detail, name="tmdb_detail"),
    path('genre_recommends/<int:genre_ids>/', views.genre_recommends, name="genre_recommends"),
    path('<int:movie_id>/similar', views.ranked_similar, name="ranked_similar"),    
    path('<str:username>/rank_list/', views.rank_list, name='rank_list'),
]

movies/models.py
from django.db import models
from django.conf import settings

class Movie(models.Model):
    movie_id = models.CharField(max_length=100)
    title = models.CharField(max_length=100)
    released_date = models.CharField(max_length=50)
    popularity = models.DecimalField(max_digits=7, decimal_places=3)
    vote_average = models.DecimalField(max_digits=2, decimal_places=1)
    overview = models.TextField()
    poster_path = models.CharField(max_length=500)
    genre_ids = models.CharField(max_length=50)

    def __str__(self):
        return self.title

class MovieReview(models.Model):
    RANKS = [
        (1, '★'),
        (2, '★★'),
        (3, '★★★'),
        (4, '★★★★'),
        (5, '★★★★★'),
    ]
    content = models.CharField(max_length=100)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    rank = models.IntegerField(choices=RANKS, default=5)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.content

movies/forms.py
from django import forms
from .models import Movie, MovieReview

class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = '__all__'


class MovieReviewForm(forms.ModelForm):
    class Meta:
        model = MovieReview
        fields = ('content', 'rank',)

movies/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_safe, require_POST, require_http_methods
from django.contrib.auth.decorators import login_required
from .models import Movie, MovieReview
from .forms import MovieReviewForm
from django.core.paginator import Paginator
from django.contrib.auth import get_user_model
@require_http_methods(['GET', 'POST'])
def main(request):
    context= {
    }
    return render(request, 'main.html', context)

@require_safe
def movie_detail(request, movie_pk):
    movie = get_object_or_404(Movie, pk=movie_pk)
    review_form = MovieReviewForm()
    reviews = movie.moviereview_set.order_by('-pk')
    context = {
        'movie': movie,
        'review_form': review_form,
        'reviews': reviews,
    }
    return render(request, 'movies/detail.html', context)


@require_POST
def movie_review_create(request, movie_pk):
    movie = get_object_or_404(Movie, pk=movie_pk)
    if request.user.is_authenticated:
        review_form = MovieReviewForm(request.POST)
        if review_form.is_valid():
            review = review_form.save(commit=False)
            review.movie = movie
            review.user = request.user
            review.save()
    return redirect('movies:movie_detail', movie.pk)


@login_required
def movie_review_update(request, movie_pk, review_pk):
    movie = get_object_or_404(Movie, pk=movie_pk)
    review = get_object_or_404(MovieReview, pk=review_pk)
    if request.method == 'POST':
        review_form = MovieReviewForm(request.POST, instance=review)
        if review_form.is_valid():
            review_tmp = review_form.save(commit=False)
            review_tmp.user = request.user
            review_tmp.save()
            context = {
                'review_tmp': review_tmp,
            }
            return redirect('movies:movie_detail', movie_pk)
    else:
        review_form = MovieReviewForm(instance=review)
    context = {
        'movie': movie,
        'review_tmp': review,
        'review_form': review_form,
    }
    return render(request, 'movies/detail.html', context)


@require_POST
def movie_review_delete(request, movie_pk, review_pk):
    if request.user.is_authenticated:
        review = get_object_or_404(MovieReview, pk=review_pk)
        if request.user == review.user:
            review.delete()
    return redirect('movies:movie_detail', movie_pk)

# -----------------------tmdb API-----------------------
# tmdb에 데이터를 받아오기 위한 함수
import requests

class TMDBHelper:
    def __init__(self, api_key=None):
        self.api_key = api_key
    # url 작성하기
    def get_request_url(self, method, **kwargs):
        base_url = 'https://api.themoviedb.org/3'
        request_url = base_url + method
        request_url += f'?api_key={self.api_key}'

        for k, v in kwargs.items():
            request_url += f'&{k}={v}'

        return request_url
    # 영화 제목 입력하면 id값 받아오기
    def get_movie_id(self, title):
        request_url = self.get_request_url('/search/movie', query=title, region='KR', language='ko')
        data = requests.get(request_url).json()
        results = data.get('results')
        if results:
            movie = results[0]
            movie_id = movie['id']
            return movie_id
        else:
            return None

tmdb_helper = TMDBHelper('6163fbe091536a27c8951c10ecb40d6c')

@require_safe
# 영화 목록(영화 평점 기능을 위해 상시 Local DB 사용)
def movie_list(request):
    # tmdb API로 가져오는 영화 목록 (영화에 평점다는 명세서 요구사항으로 인해 주석처리)
    # url = tmdb_helper.get_request_url('/movie/top_rated',region='KR', language='ko')
    # data = requests.get(url).json()
    # movies = []
    
    # genres_url = tmdb_helper.get_request_url('/genre/movie/list', region='KR', language='ko')
    # genres_list = requests.get(genres_url).json()
    # if 'results' in data : 
    #     for i in range(1, 11):
    #         tmp_url = url + '&page=' + str(i)
    #         movies_json = requests.get(tmp_url).json()
    #         for movie in movies_json['results']:
    #             movies.append(movie)
       
    #     genres_url = tmdb_helper.get_request_url('/genre/movie/list', region='KR', language='ko')
    #     genres_list = requests.get(genres_url).json()
    #     genres = genres_list['genres']
    #     for movie in movies:
    #         for i in range(len(movie['genre_ids'])):
    #             for j in range(len(genres)):
    #                 if movie['genre_ids'][i] == genres[j]['id']:
    #                     movie['genre_ids'][i] = genres[j]['name']
    #         data_results_start = data['results'][0]
    #         data_results_end = data['results'][1:]
    #         paginator = Paginator(movies, 10)
    #         page = request.GET.get('page')
    #         paginators = paginator.get_page(page)
    #     context = {
    #         'paginators': paginators,
    #         'movies': movies,
    #         'movie_start': data_results_start,
    #         'movie_end': data_results_end,
    #         'page_name': '영화 목록'
    #     }
    #     return render(request, 'movies/tmdb_list_form.html', context)
    # else:
    movies_1 = Movie.objects.order_by('-release_date')[1:60] 
    movies1_start = Movie.objects.order_by('-release_date')[0]
    
    movies = Movie.objects.order_by('-release_date')
    paginator = Paginator(movies, 10)
    page = request.GET.get('page')
    paginators = paginator.get_page(page)
    context = {
        'movies_1': movies_1,
        'movies1_start': movies1_start,
        'paginators': paginators,
        'page_name': '영화 목록'
    }
    return render(request, 'movies/movie_list.html', context)

@require_safe
# 개봉 예정 작품
def tmdb_upcoming(request):
    url = tmdb_helper.get_request_url('/movie/upcoming',region='KR', language='ko')
    data = requests.get(url).json()
    if 'results' in data : 
        data_results = data['results']
        genres_url = tmdb_helper.get_request_url('/genre/movie/list', region='KR', language='ko')
        # url에 요청한 정보를 저장
        genres_list = requests.get(genres_url).json()
        genres = genres_list['genres']
        # 장르 id를 name으로 변경
        for movie in data_results:
            for i in range(len(movie['genre_ids'])):
                for j in range(len(genres)):
                    if movie['genre_ids'][i] == genres[j]['id']:
                        movie['genre_ids'][i] = genres[j]['name']
        data_results_start = data['results'][0]
        data_results_end = data['results'][1:]

        paginator = Paginator(data_results, 10)
        page = request.GET.get('page')
        paginators = paginator.get_page(page)
    else:
        data_results_start = ''
        data_results_end = ''
        paginators = ''
        data_results = ''
    context = {
        'paginators': paginators,
        'movies': data_results,
        'movie_start': data_results_start,
        'movie_end': data_results_end,
        'page_name': '개봉 예정 영화'
    }
    return render(request, 'movies/tmdb_list_form.html', context)


# def tmdb_toprate(request):
# 높은 평점을 index 페이지로 구성
@require_safe
def movie_index(request):
    url = tmdb_helper.get_request_url('/movie/top_rateds',region='KR', language='ko')
    data = requests.get(url).json()
    if 'results' in data : 
        data_results = data['results'][:10]
        genres_url = tmdb_helper.get_request_url('/genre/movie/list', region='KR', language='ko')
        genres_list = requests.get(genres_url).json()
        genres = genres_list['genres']
        for movie in data_results:
            for i in range(len(movie['genre_ids'])):
                for j in range(len(genres)):
                    if movie['genre_ids'][i] == genres[j]['id']:
                        movie['genre_ids'][i] = genres[j]['name']
        context = {
        'movies': data_results,
        'page_name': '평점순',
        'tmdb': 1,
        }
        return render(request, 'movies/recommend_tmdb.html', context)
    # url에 요청한 정보가 잘못되거나 오프라인일 경우 Local DB로 동작
    else:
        data_results = Movie.objects.order_by('-vote_average')[:10]    
    
        context = {
            'movies': data_results,
            'page_name': '평점순'
        }
        return render(request, 'movies/index.html', context)


@require_safe
# 현재 인기작
def tmdb_popular(request):
    url = tmdb_helper.get_request_url('/movie/popular',region='KR', language='ko')
    data = requests.get(url).json()
    if 'results' in data : 
        data_results = data['results'][:10]
        genres_url = tmdb_helper.get_request_url('/genre/movie/list', region='KR', language='ko')
        genres_list = requests.get(genres_url).json()
        genres = genres_list['genres']
        for movie in data_results:
            for i in range(len(movie['genre_ids'])):
                for j in range(len(genres)):
                    if movie['genre_ids'][i] == genres[j]['id']:
                        movie['genre_ids'][i] = genres[j]['name']
        context = {
        'movies': data_results,
        'page_name': '인기 영화',
        'tmdb': 1,
        }
        return render(request, 'movies/recommend_tmdb.html', context)

    # url에 요청한 정보가 잘못되거나 오프라인일 경우 데이터가 없음(오류페이지 방지)
    else:      
        context = {
            'movies': '',
            'page_name': '인기 영화'
        }
        return render(request, 'movies/index.html', context)


@require_safe
# 현재 상영작
def tmdb_now_playing(request):
    url = tmdb_helper.get_request_url('/movie/now_playing',region='KR', language='ko')
    data = requests.get(url).json()
    if 'results' in data : 
        data_results = data['results']
        genres_url = tmdb_helper.get_request_url('/genre/movie/list', region='KR', language='ko')
        genres_list = requests.get(genres_url).json()
        genres = genres_list['genres']
        for movie in data_results:
            for i in range(len(movie['genre_ids'])):
                for j in range(len(genres)):
                    if movie['genre_ids'][i] == genres[j]['id']:

movies/templates/movies/detail.html
{% extends 'base.html' %}
{% block css %}
<style>
</style>
{% endblock css %}
{% block content %}
<h1 style="height: 50px; line-height: 50px; margin: 8px 0 0;">{{ movie.title }}</h1>
<div style="width: 1400px;">
<hr>
<div style="display: flex;">
<p style="margin-right: 30px;"><img src="https://image.tmdb.org/t/p/w500/{{ movie.poster_path }}" alt="img" style="width: 500px;"></p>
  <div style="width: 870px;">
  <p style="font-size: 35px;">줄거리</p>
  <p style="font-size: 20px;">{{ movie.overview }}</p>
  <hr>
  <p style="font-size: 20px;">개봉일</p>
  <p>
  {{ movie.release_date|date:'Y-m-d' }}
  </p>
  <hr>
  <p style="font-size: 20px;">관객수</p>
  <p>{{ movie.popularity }}K</p>
  <hr>
  <p style="font-size: 20px;">평점</p>
  <p>{{ movie.vote_average }}</p>
  <hr>
  <p id="genresList" style="font-size: 20px;">장르</p>
  <p>{{ movie.genre_ids|slice:"2:-2"|cut:"'" }}</p>
  </div>
</div>
<hr>
{% if reviews %}
  <p>{{ reviews|length }}개의 댓글이 있습니다.</p>
{% else %} 
<p>0개의 댓글이 있습니다</p>
{% endif %}
{% if request.user.is_authenticated %}
<form action="{% url 'movies:movie_review_create' movie.pk %}" method="POST">
  {% csrf_token %}
  {{ review_form }}
  <input type="submit" value="Enter">
</form>
<br>
{% endif %}

{% comment %} 댓글 목록 {% endcomment %}
{% for review in reviews %}
<hr>
  <p>작성자 : {{ review.user }}</p> 
  <p>댓글내용 : {{ review.content }}</p> 
  <p>평점 : {{ review.get_rank_display }}</p>
    <p>생성 : {{ review.created_at | date:'Y년 m월 d일 h시 i분'}} / 수정 : {{ review.updated_at | date:'Y년 m월 d일 h시 i분'}}&nbsp&nbsp</p>
  {% if user == review.user %}
    <div style="display: flex;">
    <button class="review-update-btn btn-gold" data-review-id="{{ review.pk }}" style="width: 150px; height: 40px; padding: 10px;">댓글수정</button>
    &nbsp&nbsp&nbsp
    <form action="{% url 'movies:movie_review_delete' movie.pk review.pk %}" method="POST" class="d-inline">
      {% csrf_token %}
        <button class="btn-gold" style="width: 150px; height: 40px; padding: 10px;">댓글삭제</button>
    </form>
    </div>
    <form class="review-form review-form-{{ review.pk }}" data-form-id="{{ review.pk }}" data-movie-id="{{ movie.pk }}" action="{% url 'movies:movie_review_update' movie.pk review.pk %}" method="POST" style="display: none;">    
      {% csrf_token %}
      <input type="text" class="review-input-{{ review.pk }}" name="content" maxlength="100" required="" value={{ review.content }} size=55 >
      <select class="review-input-{{ review.pk }}" name="rank" value={{ review.rank }}>
        <option value="1">★</option>
        <option value="2">★★</option>
        <option value="3">★★★</option>
        <option value="4">★★★★</option>
        <option value="5">★★★★★</option>
      </select>
      <button class="btn-gold review-btn-{{ review.pk }}" style="width: 150px; height: 40px; padding: 10px; margin-top: 10px;">수정확인</button>
    </form>
  {% endif %}
{% endfor %}
<hr>
{% endblock content %}
{% block script %}
<script>
  const buttons = document.querySelectorAll('.review-update-btn')
  const forms = document.querySelectorAll('.review-form')
  const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value

  buttons.forEach(button => {
    button.addEventListener('click', function (event) {
      event.preventDefault()
      const reviewId = event.target.dataset.reviewId
      const reviewForm = document.querySelector(`.review-form-${reviewId}`)
      if (reviewForm.style.display) {
        reviewForm.style.display = "";
      } else {
        reviewForm.style.display = "none";
      }
    })
  })
</script>
{% endblock script %}

movies/templates/movies/face_recommends.html
{% extends 'base.html' %}
{% block css %}
*{
  margin: 0;
  padding: 0;
  outline: none;
  border: none;
	box-sizing: border-box;
}
*:before,
*:after{
	box-sizing: border-box;
}
html,
body{
	min-height: 100%;
}

.container-carousel{
	margin: 4% auto;
	width: 210px;
	height: 140px;
	position: relative;
	perspective: 1000px;
}
#carousel{
	width: 100%;
	height: 100%;
	position: absolute;
	transform-style: preserve-3d;
	animation: rotation 30s infinite linear;
}
#carousel:hover{
	animation-play-state: paused;
}
#carousel figure{
	display: block;
	position: absolute;
	width: 186px;
	height: 260px;
	left: 10px;
	top: 10px;
	overflow: hidden;
}
#carousel figure:nth-child(1){transform: rotateY(0deg) translateZ(288px);}
#carousel figure:nth-child(2) { transform: rotateY(36deg) translateZ(288px);}
#carousel figure:nth-child(3) { transform: rotateY(72deg) translateZ(288px);}
#carousel figure:nth-child(4) { transform: rotateY(108deg) translateZ(288px);}
#carousel figure:nth-child(5) { transform: rotateY(144deg) translateZ(288px);}
#carousel figure:nth-child(6) { transform: rotateY(180deg) translateZ(288px);}
#carousel figure:nth-child(7) { transform: rotateY(216deg) translateZ(288px);}
#carousel figure:nth-child(8) { transform: rotateY(252deg) translateZ(288px);}
#carousel figure:nth-child(9) { transform: rotateY(288deg) translateZ(288px);}
#carousel figure:nth-child(10) { transform: rotateY(324deg) translateZ(288px);}

img{
	cursor: pointer;
	transition: all .5s ease;
}
img:hover{
	-webkit-filter: grayscale(0);
  transform: scale(0.95, 0.95);
}

@keyframes rotation{
	from{
		transform: rotateY(0deg);
	}
	to{
		transform: rotateY(-360deg);
	}
}
{% endblock css %}
{% block content %}
<h1>&nbsp&nbsp{{ page_name }}</h1>
<br>
{% comment %} 온오프라인 여부 확인 {% endcomment %}
{% if movies %}
  {% comment %} 프로필 이미지 등록 여부 확인 {% endcomment %}
  {% if request.user.profile_img %}
  <h3 style="font-weight: bold;">&nbsp&nbsp&nbsp&nbsp{{ request.user.username }}님의 연령대에 추천하는 영화는??</h3>
  <div style="display: flex; flex-direction: column; width:100%; align-items: center;">
    {% comment %} 사용자 정보 출력 {% endcomment %}
    <div style="margin-top: 50px; margin-left: -60px;">
      <img src="{{ request.user.profile_img.url }}"  alt="profile_img" style="width: 255px; height: 275px; border: solid 5px rgba(223,190,106, 1);">
      <div class="card" style="color: rgba(223,190,106,0.7); background-color: #231f20; border: none;">
        <div class="card-body" style="font-weight: bold; text-align: center;">
            <h3 class="card-title" style="font-weight: bold;">{{ request.user.username }}님의 프로필 사진</h3>
            <p class="card-text">예상 나이 : {{ age_average }}세</p>
            <p class="card-text"><small>예상 성별 : {{ gender }}</small></p>
            <hr>
        </div>
      </div>  
    </div>
    {% comment %} flex wrap을 이용해 알맞은 영화 목록 출력 {% endcomment %}
    <div style="display: flex; flex-wrap: wrap;">
      {% for movie in movies %}
        <div style=" width: 10%; margin: 0 4% 0;">
          <div style="border: solid 1px; width: 200px;">
            <a href="{% url 'movies:tmdb_detail' movie.id %}">
              <img src="https://image.tmdb.org/t/p/w500/{{ movie.poster_path }}" alt="img" style="width: 100%; height: 300px;">
            </a>
          </div>
          <br>
          <p style="text-align: center; width: 200px; margin-top: -20px;">{{ movie.title }}</p>
        </div>
        <hr>
      {% empty %}
      <p>조건에 맞는 영화가 없습니다.</p>
      {% endfor %}
    </div>
  </div>

  {% comment %} 프로필 사진 등록이 안됐을 때 {% endcomment %}
  {% else %}
  <p style="margin-left: 30px;">프로필 사진이 없습니다.</p>
  {% endif %}

{% comment %} 오프라인일 때 {% endcomment %}
{% else %}
<p>요청이 잘못되었습니다.</p>
{% endif %}
{% endblock content %}
{% block script %}
<script>
$(document).ready(function(){

$('#itemslider').carousel({ interval: 3000 });

$('.carousel-showmanymoveone .item').each(function(){
var itemToClone = $(this);

for (var i=1;i<6;i++) {
itemToClone = itemToClone.next();

if (!itemToClone.length) {
itemToClone = $(this).siblings(':first');
}

itemToClone.children(':first-child').clone()
.addClass("cloneditem-"+(i))
.appendTo($(this));
}
});
});
</script>
{% endblock script %}

movies/templates/movies/genre_recommends.html
{% extends 'base.html' %}
{% block css %}
{% endblock css %}
{% block content %}
<div style="display: flex; justify-content: center; height: 370px;">
{% for movie in movies %}
<div style=" width: 18%; margin: 0 4% 0;">
<div style="border: solid 1px;">
<a href="{% url 'movies:tmdb_detail' movie.id %}">
<img src="https://image.tmdb.org/t/p/w500/{{ movie.poster_path }}" alt="img" style="width: 100%; height: 300px;">
</a>
</div>
<br>
<p style="text-align: center;">{{ movie.title }}</p>
</div>
<hr>
{% empty %}
<div style="display: flex; align-items: center;">
{% if genre == 0 %}
장르를 선택해주세요.
{% else %}
<p>최근 영화 중 관련 장르 영화가 없습니다.</p>
{% endif %}
</div>
{% endfor %}
</div>
<hr>
{% comment %} 장르 버튼들 {% endcomment %}
  <div  style="display: flex; justify-content: center; margin-bottom: 10px;">
  <a href="{% url 'movies:genre_recommends' 28 %}"><button class="btn-gold" style="width: 200px; padding: 0; height: 50px; font-size: 20px;">액션</button></a>&nbsp&nbsp
  <a href="{% url 'movies:genre_recommends' 12 %}"><button class="btn-gold" style="width: 200px; padding: 0; height: 50px; font-size: 20px;">모험</button></a>&nbsp&nbsp
  <a href="{% url 'movies:genre_recommends' 16 %}"><button class="btn-gold" style="width: 200px; padding: 0; height: 50px; font-size: 20px;">애니매이션</button></a>&nbsp&nbsp
  <a href="{% url 'movies:genre_recommends' 878 %}"><button class="btn-gold" style="width: 200px; padding: 0; height: 50px; font-size: 20px;">SF</button></a>&nbsp&nbsp
  <a href="{% url 'movies:genre_recommends' 10752 %}"><button class="btn-gold" style="width: 200px; padding: 0; height: 50px; font-size: 20px;">전쟁</button></a>&nbsp&nbsp
  <a href="{% url 'movies:genre_recommends' 14 %}"><button class="btn-gold" style="width: 200px; padding: 0; height: 50px; font-size: 20px;">판타지</button></a>
  </div>
  <div  style="display: flex; justify-content: center; margin-bottom: 10px;">
  <a href="{% url 'movies:genre_recommends' 80 %}"><button class="btn-gold" style="width: 200px; padding: 0; height: 50px; font-size: 20px;">범죄</button></a>&nbsp&nbsp
  <a href="{% url 'movies:genre_recommends' 27 %}"><button class="btn-gold" style="width: 200px; padding: 0; height: 50px; font-size: 20px;">공포</button></a>&nbsp&nbsp
  <a href="{% url 'movies:genre_recommends' 53 %}"><button class="btn-gold" style="width: 200px; padding: 0; height: 50px; font-size: 20px;">스릴러</button></a>&nbsp&nbsp
  <a href="{% url 'movies:genre_recommends' 9648 %}"><button class="btn-gold" style="width: 200px; padding: 0; height: 50px; font-size: 20px;">미스터리</button></a>&nbsp&nbsp
  <a href="{% url 'movies:genre_recommends' 10749 %}"><button class="btn-gold" style="width: 200px; padding: 0; height: 50px; font-size: 20px;">로맨스</button></a>&nbsp&nbsp
  <a href="{% url 'movies:genre_recommends' 18 %}"><button class="btn-gold" style="width: 200px; padding: 0; height: 50px; font-size: 20px;">드라마</button></a>
  </div>
  <div style="display: flex; justify-content: center;">
  <a href="{% url 'movies:genre_recommends' 10751 %}"><button class="btn-gold" style="width: 200px; padding: 0; height: 50px; font-size: 20px;">가족</button></a>&nbsp&nbsp
  <a href="{% url 'movies:genre_recommends' 35 %}"><button class="btn-gold" style="width: 200px; padding: 0; height: 50px; font-size: 20px;">코미디</button></a>&nbsp&nbsp
  <a href="{% url 'movies:genre_recommends' 99 %}"><button class="btn-gold" style="width: 200px; padding: 0; height: 50px; font-size: 20px;">다큐멘터리</button></a>&nbsp&nbsp
  <a href="{% url 'movies:genre_recommends' 36 %}"><button class="btn-gold" style="width: 200px; padding: 0; height: 50px; font-size: 20px;">역사</button></a>&nbsp&nbsp
  <a href="{% url 'movies:genre_recommends' 10402 %}"><button class="btn-gold" style="width: 200px; padding: 0; height: 50px; font-size: 20px;">음악</button></a>&nbsp&nbsp
  <a href="{% url 'movies:genre_recommends' 37 %}"><button class="btn-gold" style="width: 200px; padding: 0; height: 50px; font-size: 20px;">서부</button></a>
  </div>
{% endblock content %}
{% block script %}
{% endblock script %}