accounts/urls.py
from django.urls import path
from . import views

app_name="accounts"
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('change/', views.change, name='change'),
    path('delete/', views.delete, name='delete'),
    path('<str:username>/', views.profile, name='profile'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
    path('change/password/', views.password, name="password"),
]

community/urls.py
from django.urls import path
from . import views

app_name="community"
urlpatterns = [
    path('', views.community_index, name='community_index'),
    path('create/', views.community_create, name='community_create'),
    path('<int:post_pk>/', views.community_detail, name='community_detail'),
    path('<int:pk>/update/', views.community_update, name='community_update'),
    path('<int:pk>/delete/', views.community_delete, name='community_delete'),
    path('<int:post_pk>/comments/<int:comment_pk>/update/', views.community_comment_update, name='community_comment_update'),
    path('<int:post_pk>/comments/<int:comment_pk>/delete/', views.community_comment_delete, name='community_comment_delete'),
    path('<int:post_pk>/comments/create/', views.community_comment_create, name='community_comment_create'),
    path('<int:post_pk>/likes/', views.community_likes, name='community_likes'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from movies import views

urlpatterns = [
    path('', views.main, name="main"),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('community/', include('community.urls')),
    path('movies/', include('movies.urls'))
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

community/models.py
from django.db import models
from django.conf import settings
from django.db.models.deletion import CASCADE

class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=20)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    community_img = models.ImageField(upload_to='', blank=True, null=True)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_post')


    def __str__(self):
        return self.title

class CommunityComment(models.Model):
    content = models.CharField(max_length=100)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


    def __str__(self):
        return self.content

community/forms.py
from django import forms
from .models import Post, CommunityComment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'content', 'community_img')


class CommunityCommentForm(forms.ModelForm):
    class Meta:
        model = CommunityComment
        fields = ('content',)

community/views.py
from django.core import paginator
from .forms import PostForm, CommunityCommentForm
from community.models import Post, CommunityComment
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_http_methods, require_POST, require_safe
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.core.paginator import Paginator

@require_safe
def community_index(request):
    posts = Post.objects.order_by('-pk')
    paginator = Paginator(posts, '10')
    page = request.GET.get('page')
    paginators = paginator.get_page(page)
    context = {
        'posts': posts,
        'paginators': paginators,
    }
    return render(request, 'community/index.html', context)


@login_required
@require_http_methods(['GET', 'POST'])
def community_create(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            return redirect('community:community_detail', post.pk)
    else:
        form = PostForm()
    context = {
        'form': form,
        'site_name': '게시글 작성',
        'btn_name': '작성하기',
    }
    return render(request, 'community/form.html', context)


@require_safe
def community_detail(request, post_pk):
    post = get_object_or_404(Post, pk=post_pk)
    comment_form = CommunityCommentForm()
    comments = post.communitycomment_set.order_by('-pk')
    context = {
        'post': post,
        'comment_form': comment_form,
        'comments': comments,
    }
    return render(request, 'community/detail.html', context)


@login_required
@require_http_methods(['GET', 'POST'])
def community_update(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            form.save()
            return redirect('community:community_detail', post.pk)
            
    else:
        form = PostForm(instance=post)
    context = {
        'post': post,
        'form': form,
        'site_name': '게시글 수정',
        'btn_name': '수정하기',
    }
    return render(request, 'community/form.html', context)


@login_required
@require_POST
def community_delete(request, pk):
    if request.user.is_authenticated:
        community = get_object_or_404(Post, pk=pk)
        if request.user == community.user:
            community.delete()
    return redirect('community:community_index')

@require_POST
def community_comment_create(request, post_pk):
    if request.user.is_authenticated:
        post = get_object_or_404(Post, pk=post_pk)
        comment_form = CommunityCommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.post = post
            comment.user = request.user
            comment.save()
        # return JsonResponse(comment)
        return redirect('community:community_detail', post.pk)
    return redirect('accounts:login')


@login_required
def community_comment_update(request, post_pk, comment_pk):
    post = get_object_or_404(Post, pk=post_pk)
    comment = get_object_or_404(CommunityComment, pk=comment_pk)
    if request.method == 'POST':
        comment_form = CommunityCommentForm(request.POST, instance=comment)
        if comment_form.is_valid():
            comment_tmp = comment_form.save(commit=False)
            comment_tmp.user = request.user
            comment_tmp.save()
            context = {
                'comment_tmp': comment_tmp,
            }
            # return JsonResponse(context)
            return redirect('community:community_detail', post_pk)
    else:
        comment_form = CommunityCommentForm(instance=comment)
    context = {
        'post': post,
        'comment_tmp': comment,
        'comment_form': comment_form,
    }
    return render(request, 'community/detail.html', context)


@require_POST
def community_comment_delete(request, post_pk, comment_pk):
    if request.user.is_authenticated:
        comment = get_object_or_404(CommunityComment, pk=comment_pk)
        if request.user == comment.user:
            comment.delete()
    return redirect('community:community_detail', post_pk)


@require_POST
def community_likes(request, post_pk):
    if request.user.is_authenticated:
        post = get_object_or_404(Post, pk=post_pk)
        if post.like_users.filter(pk=request.user.pk).exists():
            post.like_users.remove(request.user)
            likes = False
        else:
            post.like_users.add(request.user)
            likes = True
        context = {
            'likes': likes,
            'count': post.like_users.count(),
        }
        return JsonResponse(context)
    return redirect('accounts:login')

community/templates/community/detail.html
{% extends 'base.html' %}
{% block css %}
{% endblock css %}
{% block content %}
<div style="display: flex; margin: 0;">
  <h1 style="margin: 5px;">{{ post.title }}&nbsp</h1> 
  {% comment %} 좋아요 / 좋아요 취소 {% endcomment %}
    <form class="like-form" data-post-id="{{ post.pk }}" style="height: 40px; margin-top: 8px;">
      {% csrf_token %}
      {% if user in post.like_users.all %}
        <button id="like-button-{{ post.pk }}" class="btn-gold" style="width: 120px; padding: 10px;">좋아요 취소</button>
      {% else %}
        <button id="like-button-{{ post.pk }}" class="btn-gold" style="width: 120px; padding: 10px;">좋아요</button>
      {% endif %}
    </form>
    &nbsp&nbsp&nbsp
    <p style="margin: 5px;">
      <span id="like-count-{{ post.pk }}" style="height: 45px; line-height: 45px;">{{ post.like_users.all|length }}</span>명이 이 글을 좋아합니다.
    </p>
</div>
<hr style="margin:0;">
<div style="padding: 5px;">
{% comment %} 게시글 사진 / 내용 {% endcomment %}
{% if post.community_img %}
<br>
<img src="{{ post.community_img.url }}" alt="community_img" style="width:500px;">
<br><br>
<p style="word-wrap: break-word; font-size: 20px; width: 100%; ">{{ post.content }}</p>
{% else %}
<p style="word-wrap: break-word; font-size: 20px; width: 100%; height: 424px;">{{ post.content }}</p>
{% endif %}
<div style="display: flex; justify-content: space-between;">
</div>
<br>
{% comment %} 게시글에서 뒤로가기 {% endcomment %}
<div style="display: flex; width: 700px; justify-content: space-between;">
  <a href="{% url 'community:community_index' %}">
  <button class="btn-gold">BACK</button>
  </a>
{% comment %} 게시글 수정, 게시글 삭제 - 게시글 작성자만 보임 {% endcomment %}
  {% if request.user == post.user %}
  <a href="{% url 'community:community_update' post.pk %}">
  <button class="btn-gold">UPDATE</button></a>
  <form action="{% url 'community:community_delete' post.pk %}" method="POST">
  {% csrf_token %}
  <button class="btn-gold">DELETE</button>
  </form>
  {% endif %} 
</div>
</div>
<hr>
<div style="display: flex; justify-content: space-between;">
<div>
{% if comments %}
  <p>{{ comments|length }}개의 댓글이 있습니다.</p>
{% else %} 
<p>0개의 댓글이 있습니다</p>
{% endif %}
{% comment %} 댓글작성 {% endcomment %}
  {% if request.user.is_authenticated %}
  <form action="{% url 'community:community_comment_create' post.pk %}" method="POST">
    {% csrf_token %}
    <label for="id_content">댓글:&nbsp</label><input type="text" name="content" maxlength="100" required="" id="id_content">
    <button class="btn-gold" style="width: 80px; height: 40px; padding: 10px; margin-top: 10px;">입력</button>
  </form>
{% endif %}

</div>
<div style="margin-top: 15px;">
<p>작성일자 : {{ post.created_at | date:'Y년 m월 d일 h시 i분' }}</p>
<p>수정일자 : {{ post.updated_at | date:'Y년 m월 d일 h시 i분' }}</p>
</div>
</div>

<div class="community-comments">
{% comment %} 댓글내용 {% endcomment %}
{% for comment in comments %}
    <hr>
  <p style="margin-top: 10px;">작성자 : {{ comment.user }}</p> 
  <p>댓글내용 : {{ comment.content }}</p> 
  <p>생성 : {{ comment.created_at | date:'Y년 m월 d일 h시 i분'}} / 수정 : {{comment.updated_at | date:'Y년 m월 d일 h시 i분'}}&nbsp&nbsp</p>

  {% comment %} 댓글내용 수정 input 열기 및 닫기 / 댓글 삭제 - 댓글 작성자만 보임{% endcomment %}
  {% if user == comment.user %}
    <div style="display: flex;">
    <button class="comment-update-btn btn-gold" data-comment-id="{{ comment.pk }}" style="width: 150px; height: 40px; padding: 10px;">댓글수정</button>
    &nbsp&nbsp&nbsp
    <form action="{% url 'community:community_comment_delete' post.pk comment.pk %}" method="POST" class="d-inline">
      {% csrf_token %}
        <button class="btn-gold" style="width: 150px; height: 40px; padding: 10px;">Delete</button>
    </form>
    </div>
    {% comment %} 댓글 수정 input (처음엔 없고 댓글수정 버튼을 누르면 ON / OFF (JS로 구현)) {% endcomment %}
    <form class="comment-form comment-form-{{ comment.pk }}" data-form-id="{{ comment.pk }}" data-post-id="{{ post.pk }}" action="{% url 'community:community_comment_update' post.pk comment.pk %}" method="POST" style="display: none;">    
      {% csrf_token %}
      <input type="text" class="comment-input-{{ comment.pk }}" name="content" maxlength="100" required="" value={{ comment.content }} size=55 >
      <button class="btn-gold comment-btn-{{ comment.pk }}" style="width: 150px; height: 40px; padding: 10px; margin-top: 10px;">수정확인</button>
    </form>
  {% endif %}
{% endfor %}
</div>

<hr>
{% endblock %}

{% block script %}
<script>
  {% comment %} 댓글 작성 {% endcomment %}

  {% comment %} 댓글 수정 {% endcomment %}

  const buttons = document.querySelectorAll('.comment-update-btn')
  const formsUpdate = document.querySelectorAll('.comment-form')
  const csrftokenUpdate = document.querySelector('[name=csrfmiddlewaretoken]').value

  {% comment %} 댓글 input 나타나게 하는 JS {% endcomment %}
  buttons.forEach(button => {
    button.addEventListener('click', function (event) {
      event.preventDefault()
      const commentId = event.target.dataset.commentId
      const commentForm = document.querySelector(`.comment-form-${commentId}`)
      if (commentForm.style.display) {
        commentForm.style.display = "";
      } else {
        commentForm.style.display = "none";
      }
      console.log('!!!!')
    })
  })

  {% comment %} 좋아요 {% endcomment %}

  const formsLike = document.querySelectorAll('.like-form')
  const csrftokenLike = document.querySelector('[name=csrfmiddlewaretoken]').value
  formsLike.forEach(form => {
    form.addEventListener('submit', function (event) {
      event.preventDefault()
      const postId = event.target.dataset.postId

      axios({
        method: 'post',
        url: `http://127.0.0.1:8000/community/${postId}/likes/`,
        headers: {'X-CSRFToken': csrftokenLike},
      })
        .then(response => {
          const likes = response.data.likes
          const likeButton = document.querySelector(`#like-button-${postId}`)
          const likeCount = document.querySelector(`#like-count-${postId}`)
          const count = response.data.count

          if (likes === true) {
            likeButton.innerText = '좋아요 취소'
          } else {
            likeButton.innerText = '좋아요'
          }
          likeCount.innerText = count
        })
    })
  })
</script>
{% endblock script %}

community/templates/community/form.html
{% extends 'base.html' %}
{% block css %}
<div class="filebox">
  <label for="ex_file">업로드</label>
  <input type="file" id="ex_file">
</div>

{% comment %} .input-file-button > input[type="file"]{
  display: inline-block;
  background: transparent;
  text-transform: uppercase;
  font-weight: 500;
  font-style: normal;
  font-size: 0.8rem;
  letter-spacing: 0.3em;
  color: rgba(223,190,106,0.7);
  border-radius: 0;
  padding: 18px 80px 20px;
  transition: all 0.7s ease-out;
  background: linear-gradient(270deg, rgba(223,190,106,0.8), rgba(146,111,52,0.8), rgba(34,34,34,0), rgba(34,34,34,0));
  background-position: 1% 50%;
  background-size: 300% 300%;
  text-decoration: none;
  margin: 0;
  border: none;
  border: 1px solid rgba(223,190,106,0.3);
} {% endcomment %}
{% endblock css %}
{% block content %}
<h1>{{ site_name }}</h1>
<hr>
<form action="" method="POST" enctype="multipart/form-data">
{% csrf_token %}
<p><label for="id_title">제목</label></p>
<input type="text" name="title" maxlength="20" required="" id="id_title" value="{{ post.title }}" style="margin-bottom: 5px;">
<p><label for="id_content">내용</label> <textarea name="content" style="width: 100%;" rows="10" required="" id="id_content">{{ post.content }}</textarea></p>
<p class="filebox"><label for="id_community_img">이미지:</label><input type="file" name="community_img" accept="image/*" id="id_community_img"></p>
<div>
<input type="checkbox" name="community_img-clear" id="community_img-clear_id">
<label for="community_img-clear_id">사진삭제</label><br>
</div>
<br>
<button class="btn-gold">{{ btn_name }}</button>
&nbsp&nbsp

{% if site_name == "게시글 작성" %}
<a href="{% url 'community:community_index' %}">
<button type="button" class="btn-gold">뒤로가기</button>
</a>

{% else %}
<a href="{% url 'community:community_detail' post.pk  %}">
<button type="button" class="btn-gold">뒤로가기</button>
</a>

{% endif %}
</form>
{% endblock %}

community/templates/community/index.html
{% extends 'base.html' %}
{% block css %}
{% endblock %}
{% block content %}
<h1>커뮤니티</h1>
<br>
<a href="{% url 'community:community_create' %}">
<button class="btn-gold">작성하기</button>
</a>
<br>
<br>
<hr>
<div id="list" class="container px-0;">
  <div>
    <div style="display: flex">
      <p style="width: 10%;">번호</p>
      <p style="width: 70%;">제목</p>
      <p style="width: 10%;">글쓴이</p>
      <p style="width: 20%;">등록일</p>
    </div>
    <div style="height: 536px;">
    {% for post in paginators %}
      <div style="display: flex; margin-top: 10px;">
          <p style="width: 10%;">{{ post.pk }}</p>
          <p style="width: 70%; text-overflow: ellipsis;"><a href="{% url 'community:community_detail' post.pk %}">{{ post.title }}</a></p>    
        <p style="width: 10%;"><a href="{% url 'accounts:profile' post.user %}">{{ post.user }}</a></p>
        <p style="width: 20%;">{{ post.created_at | date:'Y년 m월 d일 h시 i분' }}</p>
      </div>
    {% endfor %}
    </div>
  </div>
  {% comment %} pagination {% endcomment %}
  <div class="row mt-2">
    <div class="col-12">
      <nav>
        <ul class="pagination justify-content-center">
          {% if paginators.has_previous %}
            <li class="page-item">
              <a class="page-link btn-gold" href="?page={{ paginators.previous_page_number }}" style="padding: 18px 30px 18px;"><</a>
            </li>

          {% else %}
          <li class="page-item disabled">
            <a class="page-link btn-gold" href="#" style="width: 20px; padding: 18px 30px 18px; background-color: rgba(223,190,106,0.4); border: 1px solid rgba(223,190,106,0.3);"><</a>
          </li>

          {% endif %}

          {% if paginators.number|add:'-4' > 1 %}
            <li class="btn-gold" style="padding: 18px 30px 18px;">…</li>
          {% endif %}

          {% for i in paginators.paginator.page_range %}
            {% if paginators.number == i %}
              <li class="page-link btn-gold active" style="background-color: rgba(223,190,106,0.4); padding: 18px 30px 18px;">{{ i }}</li>
            {% elif i > paginators.number|add:'-3' and i < paginators.number|add:'3' %}
              <li class="page-item"><a class="page-link btn-gold" href="?page={{ i }}" style="padding: 18px 30px 18px;">{{ i }}</a></li>
            {% endif %}
          {% endfor %}

          {% if paginators.paginator.num_pages > paginators.number|add:'4' %}
            <li class="btn-gold" style="padding: 18px 30px 18px;">…</li>
          {% endif %}

          {% if paginators.has_next %}
            <li class="page-item">
              <a class="page-link btn-gold" href="?page={{ paginators.next_page_number }}" style="padding: 18px 30px 18px;">></a>
            </li>

          {% else %}
          <li class="page-item disabled">
            <a class="page-link btn-gold" href="#" style="padding: 18px 30px 18px; background-color: rgba(223,190,106,0.4); border: 1px solid rgba(223,190,106,0.3);">></a>
          </li>

          {% endif %}
        </ul>
      </nav>
    </div>
  </div>
</div>
{% endblock %}