accounts/urls.py
from django.urls import path
from . import views

app_name="accounts"
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('change/', views.change, name='change'),
    path('delete/', views.delete, name='delete'),
    path('<str:username>/', views.profile, name='profile'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
    path('change/password/', views.password, name="password"),
]

community/urls.py
from django.urls import path
from . import views

app_name="community"
urlpatterns = [
    path('', views.community_index, name='community_index'),
    path('create/', views.community_create, name='community_create'),
    path('<int:post_pk>/', views.community_detail, name='community_detail'),
    path('<int:pk>/update/', views.community_update, name='community_update'),
    path('<int:pk>/delete/', views.community_delete, name='community_delete'),
    path('<int:post_pk>/comments/<int:comment_pk>/update/', views.community_comment_update, name='community_comment_update'),
    path('<int:post_pk>/comments/<int:comment_pk>/delete/', views.community_comment_delete, name='community_comment_delete'),
    path('<int:post_pk>/comments/create/', views.community_comment_create, name='community_comment_create'),
    path('<int:post_pk>/likes/', views.community_likes, name='community_likes'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from movies import views

urlpatterns = [
    path('', views.main, name="main"),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('community/', include('community.urls')),
    path('movies/', include('movies.urls'))
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

movies/urls.py
from django.urls import path
from . import views

app_name="movies"
urlpatterns = [
    path('', views.movie_index, name='movie_index'),
    path('<int:movie_pk>/', views.movie_detail, name='movie_detail'),
    path('<int:movie_pk>/reviews/<int:review_pk>/update/', views.movie_review_update, name='movie_review_update'),
    path('<int:movie_pk>/reviews/<int:review_pk>/delete/', views.movie_review_delete, name='movie_review_delete'),
    path('<int:movie_pk>/reviews/create/', views.movie_review_create, name='movie_review_create'),
    path('list/', views.movie_list, name='movie_list'),
    # tmdb
    path('tmdb_upcoming/', views.tmdb_upcoming, name="tmdb_upcoming"),
    path('tmdb_popular/', views.tmdb_popular, name="tmdb_popular"),
    path('tmdb_now_playing/', views.tmdb_now_playing, name="tmdb_now_playing"),
    path('face_recommends/', views.face_recommends, name="face_recommends"),
    path('tmdb_search/', views.tmdb_search, name="tmdb_search"),
    path('tmdb_detail/<int:movie_id>/', views.tmdb_detail, name="tmdb_detail"),
    path('genre_recommends/<int:genre_ids>/', views.genre_recommends, name="genre_recommends"),
    path('<int:movie_id>/similar', views.ranked_similar, name="ranked_similar"),    
    path('<str:username>/rank_list/', views.rank_list, name='rank_list'),
]

accounts/models.py
from django.contrib.auth.base_user import AbstractBaseUser
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
        followings = models.ManyToManyField('self', symmetrical=False, related_name='followers')
        profile_img = models.ImageField(upload_to='', blank=True, null=True)
        password_confirm = models.CharField(max_length=128, verbose_name='password_confirm')

community/models.py
from django.db import models
from django.conf import settings
from django.db.models.deletion import CASCADE

class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=20)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    community_img = models.ImageField(upload_to='', blank=True, null=True)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_post')


    def __str__(self):
        return self.title

class CommunityComment(models.Model):
    content = models.CharField(max_length=100)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


    def __str__(self):
        return self.content

movies/models.py
from django.db import models
from django.conf import settings

class Movie(models.Model):
    movie_id = models.CharField(max_length=100)
    title = models.CharField(max_length=100)
    released_date = models.CharField(max_length=50)
    popularity = models.DecimalField(max_digits=7, decimal_places=3)
    vote_average = models.DecimalField(max_digits=2, decimal_places=1)
    overview = models.TextField()
    poster_path = models.CharField(max_length=500)
    genre_ids = models.CharField(max_length=50)

    def __str__(self):
        return self.title

class MovieReview(models.Model):
    RANKS = [
        (1, '★'),
        (2, '★★'),
        (3, '★★★'),
        (4, '★★★★'),
        (5, '★★★★★'),
    ]
    content = models.CharField(max_length=100)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    rank = models.IntegerField(choices=RANKS, default=5)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.content

accounts/forms.py
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from django.contrib.auth import get_user_model


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('username', 'password1', 'password2', 'email')

class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ('password', 'email', 'profile_img')

accounts/views.py
from django.http.response import JsonResponse
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.shortcuts import get_object_or_404, redirect, render
from .forms import CustomUserCreationForm, CustomUserChangeForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import update_session_auth_hash, get_user_model
from django.views.decorators.http import require_http_methods, require_safe, require_POST
from django.contrib.auth.decorators import login_required

@require_http_methods(['GET', 'POST'])
def signup(request):
    if not request.user.is_authenticated:
        if request.method == 'POST':
            form = CustomUserCreationForm(request.POST)
            if form.is_valid():
                user = form.save()
                auth_login(request, user)
                return redirect('movies:movie_index')
        else:
            form = CustomUserCreationForm()
        context = {
            'form': form,
        }
        return render(request, 'accounts/signup.html', context)
    # 이미 로그인이 돼있으면 index로 redirect
    else:
        return redirect('movies:movie_index')


@require_http_methods(['GET', 'POST'])
def login(request):
    if not request.user.is_authenticated:
        if request.method == 'POST':
            form = AuthenticationForm(request, request.POST)
            if form.is_valid():
                auth_login(request, form.get_user())
                return redirect(request.GET.get('next') or 'movies:movie_index')
        else:
            form = AuthenticationForm()
        context = {
            'form': form,
        }
        return render(request, 'accounts/login.html', context)
    else:
        return redirect('movies:movie_index')

@require_POST
def logout(request):
    if request.user.is_authenticated:
        auth_logout(request)
    return redirect('movies:movie_index')


@login_required
def change(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('accounts:profile', request.user)
    else:
    	form = CustomUserChangeForm(instance=request.user)
    context = {
    	'form':form,
    }
    return render(request, 'accounts/change.html', context)


@require_POST
def delete(request):
    if request.user.is_authenticated:
        request.user.delete()
        auth_logout(request)
    return redirect('accounts:login')


@require_safe
def profile(request, username):
    person = get_object_or_404(get_user_model(), username=username)
    context = {
        'person': person,
    }
    return render(request, 'accounts/profile.html', context)

@require_POST
def follow(request, user_pk):
    if request.user.is_authenticated:
        person = request.user
        another = get_object_or_404(get_user_model(), pk=user_pk)
        if another != person:
            if another.followers.filter(pk=person.pk).exists():
                another.followers.remove(person)
                isFollowed = False
            else:
                another.followers.add(person)
                isFollowed = True
            data = {
                'isFollowed': isFollowed,
                'followings_cnt': another.followings.count(),
                'followers_cnt': another.followers.count(),
            }
            return JsonResponse(data)
        return redirect('accounts:profile', another.username)
    return redirect('accounts:login')

@login_required
@require_http_methods(['GET', 'POST'])
def password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('accounts:change')
    else:
        form = PasswordChangeForm(request.user)
    context = {
        'form': form,
    }
    return render(request, 'accounts/password.html', context)

accounts/templates/accounts/change.html
{% extends 'base.html' %}
{% block content %}
<h1>회원정보수정</h1>
<hr>
<form action="{% url 'accounts:change' %}" method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  <p><label for="id_email">이메일:</label> <input type="email" name="email" value="{{ user.email }}" maxlength="254" id="id_email"></p>
  <br>
  <p><label for="id_profile_img">프로필사진:&nbsp</label>
  {% if user.profile_img %}
    <a href="http://127.0.0.1:8000/media/{{ user.profile_img }}">{{ user.profile_img }}</a>
  {% else %}
    없음
  {% endif %}
  </p>
  <div>
    <input type="checkbox" name="profile_img-clear" id="profile_img-clear_id">
    <label for="profile_img-clear_id">사진삭제</label><br>
  </div>
  <br><p>
  프로필사진 변경:
  <input type="file" name="profile_img" accept="image/*" id="id_profile_img"></p>
  <br>
  <div style="display: flex;">
    <button class="btn-gold">정보수정</button>
    &nbsp&nbsp&nbsp
    <a href="{% url 'accounts:password' %}">
      <button type="button" class="btn-gold">비밀번호 변경</button>
    </a>
  </div>
</form>
<br>
<form action="{% url 'accounts:delete' %}" method="POST">
{% csrf_token %}
<button class="btn-gold">회원탈퇴</button>
</form>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% block content %}
<h1>Login</h1>
<hr>
<form action="" method="POST">
{% csrf_token %}
<p><label for="id_username">Username:</label> <input type="text" name="username" autofocus="" autocapitalize="none" autocomplete="username" maxlength="150" required="" id="id_username"></p>
<p><label for="id_password">Password:</label> <input type="password" name="password" autocomplete="current-password" required="" id="id_password"></p>
<button  class="btn-gold">Login</button>
</form>
{% endblock %}

accounts/templates/accounts/password.html
{% extends 'base.html' %}
{% block content %}
<h1>비밀번호 변경</h1>
<hr>
<form action="{% url 'accounts:password' %}" method="POST">
{% csrf_token %}
<p><label for="id_old_password">현재 비밀번호:</label> <input type="password" name="old_password" autocomplete="current-password" autofocus="" required="" id="id_old_password"></p>
<p><label for="id_new_password1">새로운 비밀번호:</label> <input type="password" name="new_password1" autocomplete="new-password" required="" id="id_new_password1">
<p><label for="id_new_password2">새로운 비밀번호 확인:</label> <input type="password" name="new_password2" autocomplete="new-password" required="" id="id_new_password2"></p>
<button class="btn-gold">비밀번호 변경</button>
</form>
{% endblock content %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div style="display: flex;">
<h1>{{ person.username }}</h1>&nbsp&nbsp&nbsp&nbsp&nbsp
{% comment %} 본인 프로필 페이지일 경우 회원정보 수정, 타인 프로필 페이지일 경우 팔로우/언팔로우 버튼 생성 {% endcomment %}
{% if request.user == person %}
<a href="{% url 'accounts:change' %}"><button class="btn-gold" style="width: 150px; height: 40px; padding: 10px;">회원정보 수정</button></a>
&nbsp&nbsp&nbsp
{% else %}
<div>
  <form id="follow-form" data-user-id="{{ person.pk }}" data-request-user-name="{{ request.user }}" data-request-user-img="{{ request.user.profile_img }}" style="margin-top: 5px;">
        {% csrf_token %}
        {% if user in person.followers.all %}
          <button class="btn-gold" style="width: 120px; padding: 10px;">언팔로우</button>
        {% else %}
          <button class="btn-gold" style="width: 120px; padding: 10px;">팔로우</button>
        {% endif %}
      </form>
</div>
{% endif %}
</div>
{% comment %} 게시글의 개수, 팔로우 수, 팔로워 수 {% endcomment %}
<hr style="margin-top: 8px;">
<div style="display: flex;">
<span>게시글 : {{ person.post_set.all|length }}</span>
,&nbsp&nbsp&nbsp
{% with followings=person.followings.all followers=person.followers.all %}
  <div id="follow-cnt">
    <div><a href="#"data-bs-toggle="modal" data-bs-target="#exampleModal-followings" class="follow">팔로우 : {{ followings|length }}</a>
    ,&nbsp&nbsp&nbsp<a href="#" data-bs-toggle="modal" data-bs-target="#exampleModal-followers" class="follower">팔로워 : {{ followers|length }}</a></div>
  </div>
{% endwith %}
</div>
{% if person.email %}
<br>
<span>이메일 : {{ person.email }}</span>
{% endif %}
{% if person.profile_img %}
<br>
<br>
  <p>프로필 사진</p>
  <img src="{{ person.profile_img.url }}" alt="profile_img" style="width: 300px; height: 300px;">
{% endif %}
<hr>
{% comment %} 유저가 작성한 글, 댓글, 좋아요, 평점 남긴 영화 {% endcomment %}
<h3>{{ person.username }}가 작성한 글</h3>
{% for post in person.post_set.all %}
<p><a href="{% url 'community:community_detail' post.pk %}">{{ post.title }}</a></p>
{% empty %}
<p>작성한 글이 없습니다.</p>
{% endfor %}
<hr>
<h3>{{ person.username }}가 작성한 댓글</h3>
{% for comment in person.communitycomment_set.all %}
<p><a href="{% url 'community:community_detail' comment.post.pk %}">{{ comment.content }}</a></p>
{% empty %}
<p>작성한 댓글이 없습니다.</p>
{% endfor %}
<hr>
<h3>{{ person.username }}가 좋아요 누른 글</h3>
{% for post in person.like_post.all %}
<p><a href="{% url 'community:community_detail' post.pk %}">{{ post.title }}</a></p>
{% empty %}
<p>좋아요 누른 글이 없습니다.</p>
{% endfor %}
<hr>
<h3>{{ person.username }}가 평점 남긴 영화</h3>
{% for moviereview in person.moviereview_set.all %}
<p><a href="{% url 'movies:movie_detail' moviereview.movie.pk %}">{{ moviereview.movie.title }} / 내용 : {{ moviereview.content }} / 평점 : {{ moviereview.get_rank_display }}</a></p>
{% empty %}
<p>평점을 남긴 영화가 없습니다.</p>
{% endfor %}

{% comment %} 팔로우와 팔로워를 눌렀을 때 나오는 modal {% endcomment %}
<div class="modal fade" id="exampleModal-followings" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" style="background-color : rgba(50, 40, 31, 0.55);">
      <div class="modal-content" style="background-color : rgba(50, 40, 31, 0.55);">
      <p style="margin: 15px 10px 0; font-size: 20px">팔로우</p>
      <hr>
      {% for follow in person.followings.all %}
      <p><a href={% url 'accounts:profile' follow.username %}>
      {% if follow.profile_img %}
      <img src="{{ follow.profile_img.url }}" alt="" style="
      width: 50px; height: 50px; 
      margin-left: 15px;
      -webkit-border-radius: 30px;">      
      {% else %}
      <img src="{% static 'images/default-profile-img.png' %}" alt=""style="
      width: 50px; height: 50px; 
      margin-left: 15px;
      -webkit-border-radius: 30px;">
      {% endif %}&nbsp&nbsp
      {{ follow.username }}
      </a></p>
      {% endfor %}      
      <button type="button" class="btn-gold" data-bs-dismiss="modal" aria-label="Close" style="">Close</button>
    </div>
  </div>
</div>
<div class="modal fade" id="exampleModal-followers" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" style="background-color : rgba(50, 40, 31, 0.55);">
      <div class="modal-content" style="background-color : rgba(50, 40, 31, 0.55);">
      <p style="margin: 15px 10px 0; font-size: 20px">팔로워</p>
      <hr>
      <div class='follower-box'>
      {% for follower in person.followers.all %}
      <p class="follow-atag-{{ follower }}"><a href={% url 'accounts:profile' follower.username %}>
      {% if follower.profile_img %}
      <img src="{{ follower.profile_img.url }}" alt="" style="
      width: 50px; height: 50px; 
      margin-left: 15px;
      -webkit-border-radius: 30px;">
      {% else %}
      <img src="{% static 'images/default-profile-img.png' %}" alt=""style="
      width: 50px; height: 50px; 
      margin-left: 15px;
      -webkit-border-radius: 30px;">
      {% endif %}&nbsp&nbsp
      {{ follower.username }}</a></p>
      {% endfor %}
      </div>
      <button type="button" class="btn-gold" data-bs-dismiss="modal" aria-label="Close" style="">Close</button>
    </div>
  </div>
</div>
{% endblock %}

{% block script %}
  <script>
    const form = document.querySelector('#follow-form')
    const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value

    form.addEventListener('submit', function (event) {
      event.preventDefault()
      const userId = event.target.dataset.userId
      const requestUserName = event.target.dataset.requestUserName
      const requestUserImg = event.target.dataset.requestUserImg

      axios({
        method: 'post',
        url: `http://127.0.0.1:8000/accounts/${userId}/follow/`,
        headers: {'X-CSRFToken': csrftoken},
      })
        .then(response => {
          const followBtn = document.querySelector('#follow-form > button')
          const isFollowed = response.data.isFollowed
          const followers_cnt = response.data.followers_cnt
          const followings_cnt = response.data.followings_cnt
          const followCountDivfollow = document.querySelector('#follow-cnt > div > .follow')
          const followCountDivfollower = document.querySelector('#follow-cnt > div > .follower')

          if (isFollowed === true) {
            const followerBox = document.querySelector('.follower-box')
            followBtn.innerText = '언팔로우'
            var parentP = document.createElement("p")
            // 팔로우 / 언팔로우 눌렀을 때 팔로워 목록에 사용자 추가 / 제거 JS
            if (requestUserImg){
            parentP.innerHTML = `<a href='http://127.0.0.1:8000/accounts/${requestUserName}/'>
            <img src="/media/${requestUserImg}" alt="" style="
            width: 50px; height: 50px; 
            margin-left: 15px;
            -webkit-border-radius: 30px;">&nbsp&nbsp&nbsp&nbsp${requestUserName}</a>`
            } else {
            parentP.innerHTML = `<a href='http://127.0.0.1:8000/accounts/${requestUserName}/'>
            <img src="/static/images/default-profile-img.png" alt="" style="
            width: 50px; height: 50px; 
            margin-left: 15px;
            -webkit-border-radius: 30px;">&nbsp&nbsp&nbsp&nbsp${requestUserName}</a>`
            }
            parentP.setAttribute("class", `follow-atag-${requestUserName}`)
            followerBox.append(parentP)
          } else {
            followBtn.innerText = '팔로우'
            const followTag = document.querySelector(`.follow-atag-${requestUserName}`)
            followTag.remove()
          }
          followCountDivfollow.innerText = `팔로우 : ${followings_cnt}`
          followCountDivfollower.innerText = `팔로워 : ${followers_cnt}`
        })
    })
  </script>
{% endblock script %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% block content %}
<h1>회원가입</h1>
<hr>
<form action="" method="POST">
{% csrf_token %}
<p><label for="id_username">아이디:</label> <input type="text" name="username" maxlength="150" autofocus="" required="" id="id_username"> 
<p><label for="id_password1">비밀번호:</label> <input type="password" name="password1" autocomplete="new-password" required="" id="id_password1"> 
<p><label for="id_password2">비밀번호 확인:</label> <input type="password" name="password2" autocomplete="new-password" required="" id="id_password2">
<p><label for="id_email">이메일:</label> <input type="email" name="email" maxlength="254" id="id_email"></p>
<button class="btn-gold">회원가입</button>
</form>
{% endblock %}