accounts/urls.py
from django.urls import path
from . import views

app_name="accounts"
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('change/', views.change, name='change'),
    path('delete/', views.delete, name='delete'),
    path('<str:username>/', views.profile, name='profile'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
    path('change/password/', views.password, name="password"),
]

community/urls.py
from django.urls import path
from . import views

app_name="community"
urlpatterns = [
    path('', views.community_index, name='community_index'),
    path('create/', views.community_create, name='community_create'),
    path('<int:post_pk>/', views.community_detail, name='community_detail'),
    path('<int:pk>/update/', views.community_update, name='community_update'),
    path('<int:pk>/delete/', views.community_delete, name='community_delete'),
    path('<int:post_pk>/comments/<int:comment_pk>/update/', views.community_comment_update, name='community_comment_update'),
    path('<int:post_pk>/comments/<int:comment_pk>/delete/', views.community_comment_delete, name='community_comment_delete'),
    path('<int:post_pk>/comments/create/', views.community_comment_create, name='community_comment_create'),
    path('<int:post_pk>/likes/', views.community_likes, name='community_likes'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from movies import views

urlpatterns = [
    path('', views.main, name="main"),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('community/', include('community.urls')),
    path('movies/', include('movies.urls'))
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

movies/urls.py
from django.urls import path
from . import views

app_name="movies"
urlpatterns = [
    path('', views.movie_index, name='movie_index'),
    path('<int:movie_pk>/', views.movie_detail, name='movie_detail'),
    path('<int:movie_pk>/reviews/<int:review_pk>/update/', views.movie_review_update, name='movie_review_update'),
    path('<int:movie_pk>/reviews/<int:review_pk>/delete/', views.movie_review_delete, name='movie_review_delete'),
    path('<int:movie_pk>/reviews/create/', views.movie_review_create, name='movie_review_create'),
    path('list/', views.movie_list, name='movie_list'),
    # tmdb
    path('tmdb_upcoming/', views.tmdb_upcoming, name="tmdb_upcoming"),
    path('tmdb_popular/', views.tmdb_popular, name="tmdb_popular"),
    path('tmdb_now_playing/', views.tmdb_now_playing, name="tmdb_now_playing"),
    path('face_recommends/', views.face_recommends, name="face_recommends"),
    path('tmdb_search/', views.tmdb_search, name="tmdb_search"),
    path('tmdb_detail/<int:movie_id>/', views.tmdb_detail, name="tmdb_detail"),
    path('genre_recommends/<int:genre_ids>/', views.genre_recommends, name="genre_recommends"),
    path('<int:movie_id>/similar', views.ranked_similar, name="ranked_similar"),    
    path('<str:username>/rank_list/', views.rank_list, name='rank_list'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<link href="https://fonts.googleapis.com/css?family=Josefin+Sans:300,400,700&subset=latin-ext" rel="stylesheet">

  <title>Document</title>
  <style>
  {% comment %} input 타입 css {% endcomment %}
  input[type="text"], input[type="password"], input[type="email"], textarea {
  color: rgba(223,190,106,0.7); background: #231f20; padding: 5px; border: solid 1px; border-color: rgba(223,190,106,0.7); line-height: 17px;
}
  input[type="file"] > button {
    color: #fff;
    border: 1px solid rgba(223,190,106,0);
    color: white;
    background-position: 99% 50%;
  }
  {% block css %}
  {% endblock css %}
  </style>
  
  <link rel="stylesheet" href="{% static "css/base.css" %}">
</head>
<body>
{% comment %} navbar {% endcomment %}
<nav style=" position:-webkit-sticky;position:sticky;top:0;z-index:1020; background: #231f20;  line-height: 70px; height: 70px; margin: 0px; display: flex; justify-content: space-between;">
  <div>
    <div style="display: flex; width: 300px; justify-content: space-between; margin-left: 20px;">
    {% comment %} 처음 출력 페이지로 이동 {% endcomment %}
      <div><a href="{% url 'main' %}">배배</a></div>
      {% comment %} dropdown형식으로 출력 {% endcomment %}
      <div class="nav-item dropdown" style="">
        <a class="nav-link dropdown" href="#" id="navbarDropdown2" role="button" data-bs-toggle="dropdown" aria-expanded="false" style="padding: 0;">    
        <p style=" justify-content: center; padding: 0;">영화 추천</p>
        </a>
        <ul class="dropdown-menu" aria-labelledby="navbarDropdown2" style="
        background-color: rgba(50, 40, 31, 1); opacity : 1; min-width: 110px;
        padding: 0;
        text-align: center;
        ">
          <a href="{% url 'movies:movie_index' %}"><button style="border: none; background-color: rgb(50, 40, 31, 1); color: rgba(223,190,106,0.7);">높은 평점</button></a>
          <a href="{% url 'movies:tmdb_popular' %}"><button style="border: none; background-color: rgb(50, 40, 31, 1); color: rgba(223,190,106,0.7);">인기 영화</button></a>
          <a href="{% url 'movies:face_recommends' %}"><button style="border: none; background-color: rgb(50, 40, 31, 1); color: rgba(223,190,106,0.7);">연령대 추천</button></a>
          <a href="{% url 'movies:genre_recommends' 0 %}"><button style="border: none; background-color: rgb(50, 40, 31, 1); color: rgba(223,190,106,0.7);">장르별 추천</button></a>
          
        </ul>
      </div>
      <div class="nav-item dropdown" style="">
        <a class="nav-link dropdown" href="#" id="navbarDropdown3" role="button" data-bs-toggle="dropdown" aria-expanded="false" style="padding: 0;">    
        <p style=" justify-content: center; padding: 0;">영화 목록</p>
        </a>
        <ul class="dropdown-menu" aria-labelledby="navbarDropdown3" style="
        background-color: rgba(50, 40, 31, 1); opacity : 1; min-width: 120px;
        padding: 0;
        text-align: center;
        ">
          <a href="{% url 'movies:movie_list' %}"><button style="border: none; background-color: rgb(50, 40, 31, 1); color: rgba(223,190,106,0.7);">전체 목록</button></a>
          <a href="{% url 'movies:tmdb_upcoming' %}"><button style="border: none; background-color: rgb(50, 40, 31, 1); color: rgba(223,190,106,0.7);">개봉 예정</button></a>
          <a href="{% url 'movies:tmdb_now_playing' %}"><button style="border: none; background-color: rgb(50, 40, 31, 1); color: rgba(223,190,106,0.7);">현재 상영 중</button></a>
          {% if request.user.is_authenticated %}
          <a href="{% url 'movies:rank_list' user.username %}"><button style="border: none; background-color: rgb(50, 40, 31, 1); color: rgba(223,190,106,0.7);">평점 남긴 영화</button></a>
          {% endif %}
        </ul>
      </div>
      <div><a href="{% url 'community:community_index' %}">커뮤니티</a></div>
    </div>
  </div>
  <div class="search" style="text-align: center;">
  {% comment %} 검색창 {% endcomment %}
  <form action="{% url 'movies:tmdb_search' %}" method="GET" style="height: 15px;">
    <label for="search-input1"></label>
    <input type="search" class='search-input1' placeholder="영화 제목을 입력하세요." name='search' size=100 style="
    color: rgba(223,190,106,0.7); background: #231f20; padding: 5px; border: solid 1px; border-color: rgba(223,190,106,0.7); line-height: 30px; margin-right: 200px;">
  </form>
  <br>
</div>
{% comment %} 계정 관련 내용을 dropdown 형식으로 출력 {% endcomment %}
  <div class="nav-item dropdown" style="margin-right: 40px;">
    <a class="nav-link dropdown" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false" style="padding: 0;">
    {% if request.user.profile_img %}
    <img src="{{ user.profile_img.url }}" alt="" style="
    width: 40px; height: 40px; 
    -webkit-border-radius: 40px;">
    {% else %}
    <img src="{% static 'images/default-profile-img.png' %}" alt=""style="
    width: 40px; height: 40px; 
    -webkit-border-radius: 40px;">
    {% endif %}
    </a>
    <ul class="dropdown-menu" aria-labelledby="navbarDropdown" style="background-color: rgba(50, 40, 31, 1); opacity : 1;">
    {% if request.user.is_authenticated %}
      <a href="{% url 'accounts:profile' request.user.username %}"><button>내 정보</button></a>
      <br>
      <form action="{% url 'accounts:logout' %}" method="POST">
        {% csrf_token %}
        <button style="
        outline: 0;
        width: 158px;
        border: 0;
        background-color : rgba(50, 40, 31, 0.55);
        color: rgba(223,190,106,0.7);">
        로그아웃</button>
      </form>
      {% else %}
      <a href="" data-bs-toggle="modal" data-bs-target="#exampleModal" data-bs-whatever="@mdo"><button>로그인</button></a>
      <br>
      <a href="{% url 'accounts:signup' %}"><button>회원가입</button></a>
      {% endif %}
    </ul>
  </div>
</nav>
{% comment %} 로그인 modal {% endcomment %}
<div class="container" style="margin-top: 15px;">
  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" style="background-color : rgba(50, 40, 31, 0.55);">
      <div class="modal-content" style="background-color : rgba(50, 40, 31, 0.55);">
        <p style="margin-left: 15px; margin-top: 20px; font-size: 30px;">로그인</p>
        <hr>
        <div class="modal-body">
          <form action="{% url 'accounts:login' %}" method="POST">
            {% csrf_token %}
            <p><label for="id_username">아이디:</label> <input type="text" name="username" autofocus="" autocapitalize="none" autocomplete="username" maxlength="150" required="" id="id_username"></p><br>
            <p><label for="id_password">비밀번호:</label> <input type="password" name="password" autocomplete="current-password" required="" id="id_password"></p>
            <br>
            <button class="btn-gold">로그인</button>
            <button type="button" class="btn-gold" data-bs-dismiss="modal" aria-label="Close" style="margin-left: 40px;">닫기</button>
          </form>
        </div>
      </div>
    </div>
  </div>
  {% block content %}  
  {% endblock content %}
</div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
  <script src="https://kit.fontawesome.com/964293759e.js" crossorigin="anonymous"></script>
  {% block script %}
  {% endblock script %}
</body>
</html>

templates/main.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<link href="https://fonts.googleapis.com/css?family=Josefin+Sans:300,400,700&subset=latin-ext" rel="stylesheet">
<style>

#slider-text{
  padding-top: 40px;
  display: block;
}
#slider-text .col-md-6{
  overflow: hidden;
}

#slider-text h2 {
  font-family: 'Josefin Sans', sans-serif;
  font-weight: 400;
  font-size: 30px;
  letter-spacing: 3px;
  margin: 30px auto;
  padding-left: 40px;
}
#itemslider h4{
  font-family: 'Josefin Sans', sans-serif;
  font-weight: 400;
  font-size: 12px;
  margin: 10px auto 3px;
}
#itemslider h5{
  font-family: 'Josefin Sans', sans-serif;
  font-weight: bold;
  font-size: 12px;
  margin: 3px auto 2px;
}
#itemslider h6{
  font-family: 'Josefin Sans', sans-serif;
  font-weight: 300;;
  font-size: 10px;
  margin: 2px auto 5px;
}


html,
body {
    height: 100%;
}

.carousel,
.item,
.active {
    height: 100%;
}

.carousel-inner {
  height: 100%;
  background: #000;
}

.carousel-caption{padding-bottom:80px;}

h2{font-size: 60px;}
p{padding:10px}

.fill {
    width: 100%;
    height: 100%;
    background-position: center;
    -webkit-background-size: cover;
    -moz-background-size: cover;
    background-size: cover;
    -o-background-size: cover;
    opacity:0.6;
}

/**
 * Button
 */
.btn-transparent {
  background: transparent;
  color: #fff;
  border: 2px solid #fff;
}
.btn-transparent:hover {
  background-color: #fff;
}

.btn-rounded {
  border-radius: 70px;
}

.btn-large {
  padding: 11px 45px;
  font-size: 18px;
}

/**
 * Change animation duration
 */
.animated {
  -webkit-animation-duration: 1.5s;
  animation-duration: 1.5s;
}

@-webkit-keyframes fadeInRight {
  from {
    opacity: 0;
    -webkit-transform: translate3d(100px, 0, 0);
    transform: translate3d(100px, 0, 0);
  }

  to {
    opacity: 1;
    -webkit-transform: none;
    transform: none;
  }
}

  .btn-gold {
    display: inline-block;
    background: transparent;
    text-transform: uppercase;
    letter-spacing: 0.3em;
    color: white;
    padding: 18px 80px 20px;
    transition: all 0.7s ease-out;
    background: linear-gradient(270deg, rgba(223,190,106,0.8), rgba(146,111,52,0.8), rgba(34,34,34,0), rgba(34,34,34,0));
    background-position: 99% 50%;
    background-size: 300% 300%;
    text-decoration: none;
    margin: 0;
    border: none;
    border: 1px solid rgba(223,190,106,0.3);
  }
  .btn-gold:hover {
    color: #fff;
    border: 1px solid rgba(223,190,106,0);
    color: white;
    background-position: 99% 50%;
  }

  .carousel-indicators li {
    border: 1px solid rgba(223,190,106,0.7);
  }

  .carousel-indicators .active {
    background-color: rgba(223,190,106,0.7);;
  }
</style>
<body>

  
  <div id="myCarousel" class="carousel slide">
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>
        {% comment %} 캐러셀 페이지 사진 및 텍스트 {% endcomment %}
        <div class="carousel-inner">
            <div class="item active">
                <div class="fill" style="background-image:url('https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=1920');"></div>
                <div class="carousel-caption">
                     <h2 class="animated fadeInLeft" style="color: rgba(223,190,106, 1); font-weight: bold;">영화 추천</h2>
                     <p class="animated fadeInUp" style="color: rgba(223,190,106, 1); font-weight: bold; font-size: 30px;">영화를 추천해드립니다.</p>
                     <p class="animated fadeInUp"><a href="{% url 'movies:movie_index' %}" class="btn btn-transparent btn-rounded btn-large btn-gold">영화 추천</a></p>
                </div>
            </div>
            <div class="item">
                <div class="fill" style="background-image:url('https://images.pexels.com/photos/3137890/pexels-photo-3137890.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=1080&w=1920');"></div>
                <div class="carousel-caption">
                     <h2 class="animated fadeInDown" style="color: rgba(223,190,106, 1); font-weight: bold;">영화 목록</h2>
                     <p class="animated fadeInUp" style="color: rgba(223,190,106, 1); font-weight: bold; font-size: 30px;">영화 전체 목록을 보여드립니다.</p>
                     <p class="animated fadeInUp"><a href="{% url 'movies:movie_list' %}" class="btn btn-transparent btn-rounded btn-large btn-gold">영화 목록</a></p>
                </div>
            </div>
            <div class="item">
                <div class="fill" style="background-image:url('https://images.pexels.com/photos/147413/twitter-facebook-together-exchange-of-information-147413.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=1080&w=1920');"></div>
                <div class="carousel-caption">
                     <h2 class="animated fadeInRight" style="color: rgba(223,190,106, 1); font-weight: bold;">영화 커뮤니티</h2>
                     <p class="animated fadeInRight" style="color: rgba(223,190,106, 1); font-weight: bold; font-size: 30px;">영화에 대한 이야기를 나누는 곳입니다.</p>
                     <p class="animated fadeInRight"><a href="{% url 'community:community_index' %}" class="btn btn-transparent btn-rounded btn-large  btn-gold">영화 커뮤니티</a></p>
                </div>
            </div>
        </div>

        <!-- Controls -->
        <a class="left carousel-control" href="#myCarousel" data-slide="prev">
            <span class="icon-prev"></span>
        </a>
        <a class="right carousel-control" href="#myCarousel" data-slide="next">
            <span class="icon-next"></span>
        </a>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>
  
</body>
</html>